name: Update CSV from Google Sheets

on:
  schedule: # Optional: Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update_csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Download CSV
        run: |
          curl -o data.csv "https://doc-0o-58-sheets.googleusercontent.com/pub/54bogvaave6cua4cdnls17ksc4/mvkosvirj17gq91guhevepulko/1738531045000/104656866105737626334/*/e@2PACX-1vSprhVOaQKUHHyW9dKmyQ3rXILs1Ci3UzPIy9XX3t9VVbu_OiAuANuFFqe7JNcGbHSWq6e4__uSWF0g?gid=0&single=true&output=csv"
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CSV data
          file_pattern: data.csv
