name: Update CSV from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download CSV
        run: |
          curl -o data.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vSprhVOaQKUHHyW9dKmyQ3rXILs1Ci3UzPIy9XX3t9VVbu_OiAuANuFFqe7JNcGbHSWq6e4__uSWF0g/pub?gid=0&single=true&output=csv"
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }} # Important: Add this back for authentication
          script: |
            const message = 'Update CSV data';
            const path = 'data.csv';
            const content = fs.readFileSync(path, 'utf8'); // Read file content

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: path,
              message: message,
              content: content,
              sha: context.sha || undefined, // Handle initial commit
              branch: context.ref.split('/')[2]
            });
