name: Update CSV from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # For manual triggering

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download CSV
        run: |
          curl -o data.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vSprhVOaQKUHHyW9dKmyQ3rXILs1Ci3UzPIy9XX3t9VVbu_OiAuANuFFqe7JNcGbHSWq6e4__uSWF0g/pub?gid=0&single=true&output=csv"
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          script: |
            const message = 'Update CSV data';
            const files = ['data.csv']; // Array of files to commit

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: files[0], // Path to the file
              message: message,
              content: fs.readFileSync(files[0], 'utf8'), // File content
              sha: context.sha, // Current commit SHA
              branch: context.ref.split('/')[2] // Current branch
            });
