name: Generate and Update iCalendar

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight (adjust as needed) 

jobs:
  generate-ical:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Choose a Node.js version

      - name: Install dependencies
        run: |
          npm install gsheets

      - name: Generate iCalendar data from Google Apps Script
        run: |
          ICALENDAR_DATA=$(npx gsheets exec 'generateIcalendarData()' \
                              --credentials-file ./credentials.json \
                              --spreadsheet-id 'YOUR_SPREADSHEET_ID')
          echo "::set-output name=ical_data::${ICALENDAR_DATA}"

      - name: Create iCalendar file
        run: |
          echo "${{ steps.generate-ical.outputs.ical_data }}" > calendar.ics

      - name: Commit and push changes
        uses: actions/checkout@v3
        with:
          push: true
