name: Update CSV from Google Sheets

on:
  schedule: # Optional: Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update_csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Download CSV
        run: |
          curl -o data.csv ""
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CSV data
          file_pattern: data.csv
